---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Create a Host
    - name: Create Host
      b1_ipam_host:
        name: "host2"
        comment: "This is created by QA"
        addresses:
          - "test1" : "10.0.0.1"
          - "test2" : "10.0.0.2"
        tags:
          - "Org": "Infoblox"
          - "Dept": "Engineering"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present
