---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "https://env-6.test.infoblox.com/"
  - api: "a466f5ed8e37bd51b4f1814a73601466"


  tasks:
    #  Gather Host
    - name: Gather Host
      b1_ipam_host_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
      register: hostlists
    - name: printing hostlists
      debug: 
        msg: " {{ hostlists }} "


