---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    # Delete the Optiongroup
    - name: Delete Option Group
      b1_ipam_option_group:
        name: "test"
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: absent