---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Create a Optionspace
    - name: Create Optionspace
      b1_ipam_option_space:
        name: "test1"
        tags:
          - "Org": "Infoblox"
          - "Dept": "QA"
        comment: "This is a test Optionspace to validate Infoblox Ansible Collection"
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: present
        
