---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "https://env-6.test.infoblox.com/"
  - api: "a466f5ed8e37bd51b4f1814a73601466"

  tasks:
    #  Gather optionspace
    - name: Gather Optionspace
      b1_ipam_option_space_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
      register: option_spaces
    - debug: msg="{{ option_spaces }}"